component_depth: 8
languages:
- name: java
  production:
    exclude:
      - .*/test/java/com/marcluque/hydra/.*\.java
  test:
    include:
      - .*/test/java/com/marcluque/hydra/.*\.java

exclude:
- /example/.*