language: java

sudo: false

script: "mvn clean compile install"

os:
- linux
- osx

jdk:
- oraclejdk8
- oraclejdk10
- openjdk11
- openjdk-ea

matrix:
  exclude:
  - os: osx
    jdk: oraclejdk8
  - os: osx
    jdk: oraclejdk10
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: oraclejdk10